### ISSUE TITLE
Timing test still flakey

### ISSUE THREAD

**Issue by knocte** [nblockchain/fsx#25]
@webwarrior-ws , we received another failure here: https://github.com/nblockchain/fsx/actions/runs/4012299515/jobs/6890632917 , I thought you had fixed this in [this commit](https://github.com/nblockchain/fsx/commit/2809b9f2301ea4c0f75ff074004ec0e7f71ebf42)? Why did it fail again?

**Comment by webwarrior-ws** [comment]
I chose error margin (5ms) based on previous failed runs. It turns out that sometimes that margin is not enough and needs to be increased.

**Comment by knocte** [comment]
What was the error margin in this instance?

**Comment by webwarrior-ws** [comment]
5.6571 ms

**Comment by webwarrior-ws** [comment]
^ that was deviation from expected result.
Error margin is still 5ms.

**Comment by knocte** [comment]
Ok I'll increase it to 10ms, thanks.
